### ISSUE TITLE
undefined error when reading getBoundingClientRect in updatePickerPosition()

### ISSUE THREAD

**Issue by admdly** [melloware/coloris-npm#106]
There is an error in `updatePickerPosition()` with the latest (0.19.0) release on npm, which appears to be due to the line added in 9af0f49 not being in the actual npm 0.19.0 release. 

Specifically, the release on GitHub includes the following check: 

https://github.com/melloware/coloris-npm/blob/9af0f49684b5d50258ad21e792b80d67d42e7a01/src/coloris.js#L351

However, the version hosted at npmjs.com, and downloaded via npm, does not:

<img width="599" alt="Screenshot 2023-04-22 at 20 02 37" src="https://user-images.githubusercontent.com/2807620/233802084-77792355-d4c5-45d3-ba0b-40ee941c4b6b.png">

This is causing the following error:
<img width="659" alt="Screenshot 2023-04-22 at 19 07 34" src="https://user-images.githubusercontent.com/2807620/233802137-f4765dc7-13ff-4313-acbe-445add232077.png">

**Comment by blutorange** [comment]
@melloware I checked and the line really is missing in the NPM release. I also did `npm pack` to build the dist files, and they do contain the line in question, so it's not an issue with the build process. So I guess it must have happened during the release process? We do have a `prepack` script that regenerates all build files from source files again, so I'm not sure what could have gone wrong. Either, seems like we just have to make a new 0.19.1 release

**Comment by melloware** [comment]
I think that was my fault.  I will release a 0.19.1 shortly.

**Comment by melloware** [comment]
OK 0.19.1 published if you don't mind checking it out.

**Comment by admdly** [comment]
Thanks for the quick turn around - I can confirm this fixes the error.

**Comment by melloware** [comment]
Thanks for reporting and confirming!
