### ISSUE TITLE
Reference to input element

### ISSUE THREAD

**Issue by pixobe** [melloware/coloris-npm#114]
**IMPORTANT:** Before reporting anything here please report it on the main project at https://github.com/mdbassit/Coloris That is the main repository where bugs should be fixed and we will port them to this project once the original Coloris project does a release.

If your issue is NPM or TypeScript related then it is OK to report that here.

Is that possible to support passing element as an input on top of query Selector for `el`? In case of shadow dom, passing the query selector might not work.

**Comment by blutorange** [comment]
This should be a feature request over at https://github.com/mdbassit/Coloris, we only package the code and add the TypeScript typings.

Currently the library really does expect a selector, and also seems to use [event delegation](https://github.com/melloware/coloris-npm/blob/main/src/coloris.js#L302). Perhaps it might be easier to specify the base element (= the shadow root) against the selector is resolved, but that can be discussed over at the main repo.
