### ISSUE TITLE
[Vue] init is not a function

### ISSUE THREAD

**Issue by matty0005** [melloware/coloris-npm#13]
Hi, after importing with npm, and adding the following to the top of the vue file
```js
import "@melloware/coloris/dist/coloris.css";
import Coloris from "@melloware/coloris";
Coloris.init();
Coloris({el: "#coloris"});
```
I get the following error.

```Uncaught (in promise) TypeError: _melloware_coloris__WEBPACK_IMPORTED_MODULE_1___default().init is not a function```

If i add the library through the CDN, it works just fine.

**Comment by melloware** [comment]
@blutorange Any thoughts on this?

**Comment by blutorange** [comment]
One question, are you using TypeScript @matty0005 ? If so, can you show your `tsconfig.json`?

**Comment by matty0005** [comment]
No, i'm not - if it helps i'm using Vue 3 (along side laravel + inertia.js).

**Comment by blutorange** [comment]
Yeah thanks for the info. I had tried this with webpack as a bundler, but that was before the package was published to npm. When I try this now, webpack seems to be doing funky things with the AMD part of the wrapper. Let me see if I can fix this.

**Comment by blutorange** [comment]
Alright, so the problem is a missing `return` which was deleted here, probably because of a merge conflict?

https://github.com/melloware/coloris-npm/commit/f8a79af374573062676415b4773e9e2d0dabc076#diff-ead9bad4168db55a026a34e4cb1a879008aef8132feb6666d49038de3669ec8aL7

So I can fix this, but let me see if I can add a simple npm `test` script we can use before publishing / after merging.

**Comment by melloware** [comment]
@matty0005 0.8.1 is on NPM now if you want to give it a try.

**Comment by matty0005** [comment]
Thanks, this now works perfectly!

**Comment by melloware** [comment]
Fantastic. Thanks for reporting.

**Comment by melloware** [comment]
@matty0005 can you update to 0.10.3 and let me know if you are getting this problem again?

**Comment by matty0005** [comment]
@melloware All seems fine - I have updated to 0.10.3 and don't seem to have any immediate issues.

**Comment by melloware** [comment]
Thanks for letting me know!
