### ISSUE TITLE
Import stylesheets into scss BUG

### ISSUE THREAD

**Issue by nuykon** [melloware/coloris-npm#135]
When I import into scss - @import "@melloware/coloris/dist/coloris.css";

Syntax Error: Error: Package path ./dist/coloris.css is not exported from package .../node_modules/@melloware/coloris (see exports field in .../node_modules/@melloware/coloris/package.json)

**Comment by melloware** [comment]
@blutorange ???

**Comment by melloware** [comment]
0.23.1 is on NPM now.
