### ISSUE TITLE
Non-passive event listener [Google Chrome]

### ISSUE THREAD

**Issue by gmunumel** [melloware/coloris-npm#52]
Hello guys, 

Thanks for the library. 

I just started using the library and as soon I opened in Google Chrome I got this warning message: 

```
coloris.js:928 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```

Any idea to remove the warning?

**Comment by jepsar** [comment]
@gmunumel this is the NPM fork. Please create your issue here https://github.com/mdbassit/Coloris
