### ISSUE TITLE
Inline colorpicker not calculating the right area dimensions

### ISSUE THREAD

**Issue by JacobDeuchert** [melloware/coloris-npm#62]
I want to display the colorpicker in a custom popup without any input. I used the following options:  
```

    Coloris({
      el: null,
      inline: true,
      parent: '#' + anchorId,
      autoClose: false,
      focusInput: false,
      alpha: false,
    })
```
![coloris](https://user-images.githubusercontent.com/43518397/165989568-a201c58a-5d25-41fd-bfa0-cf40c8e66b5b.gif)

The colorpicker opens as expected but when using the colorArea the color marker is locked to the right of the area because the x / y dimensions getting calculated are a bit off in the `updatePickerPosition()` function. I fixed it by using `getBoundingClientRect()` for the dimensions. I can provide the fix as a PR but it probably needs some testing on other use cases.

**Comment by melloware** [comment]
https://github.com/mdbassit/Coloris/issues/42

**Comment by melloware** [comment]
0.12.1 is now in NPM registry!
