### ISSUE TITLE
Readme should focus on NPM

### ISSUE THREAD

**Issue by jepsar** [melloware/coloris-npm#7]
.. remove other docs which might make it confusing to users. We should refer to the original repo for documentation.

**Comment by jepsar** [comment]
@mdbassit do you have an opinion on this?

**Comment by mdbassit** [comment]
I agree that referring to the original repo for documentation may be less confusing, but I don't mind either way.

**Comment by jepsar** [comment]
Turns out that the info on https://www.npmjs.com/package/@melloware/coloris is copied from the readme, so we'll keep it as it is.

**Comment by mdbassit** [comment]
The doc looks outdated on NPM though!

**Comment by jepsar** [comment]
@mdbassit It was updated after the release of 0.7.0. @melloware Can we force an update?

**Comment by melloware** [comment]
Yep I can just push a 0.7.1. Versions are cheap 😁
